<?php
/** @var \BetoCampoy\ChampsFramework\Router\Router $router */
$v->layout("_theme");
?>

<div class="card mb-3 text-center">
    <div class="card-header">
        <h5>Installation</h5>
    </div>
</div>

<!-- Composer -->
<div class="card mb-3">
    <div class="card-header">
        1. Composer
    </div>
    <div class="card-body">
        <p class="card-text">
            Composer is required. Access <a href="https://getcomposer.org/" target="_blank">https://getcomposer.org/</a>
            for more information.
        </p>
    </div>
</div>

<!-- composer.json -->
<div class="card mb-3">
    <div class="card-header">
        2. Create a <strong>composer.json</strong> configuration file in root ofthe project folder.
    </div>
    <div class="card-body">
        <p class="card-text">
            Example of a new <strong>composer.json</strong>
        </p>
        <card class="card border-secondary m-3">
            <div class="card-body">
                        <pre><code>
{
    "authors": [
        {
            "name": "Creator Author Name",
            "email": "author@email.com",
            "homepage": "url.of.project",
            "role": "Developer"
        }
    ],
    "description": "Description of you project",
    "config": {"vendor-dir": "vendor"},
    "autoload": {
        "psr-4": {"Source\\": "Source/"}
    },
    "require": {
        "php": "^7.4",
        "betocampoy/champs_framework": "1.0.*"
    }
}
</code></pre>
            </div>
        </card>
    </div>
</div>

<!-- .htaccess -->
<div class="card mb-3">
    <div class="card-header">
        3. Create the <strong>.htaccess</strong> file bellow in root ofthe project folder.
    </div>
    <div class="card-body">
        <p class="card-text">
            This file is needed for friendly url generated by router layer.
        </p>
        <card class="card border-secondary m-3">
            <div class="card-body">
<pre><code>
RewriteEngine On
Options All -Indexes

## ROUTER WWW Redirect.
#RewriteCond %{HTTP_HOST} !^www\. [NC]
#RewriteRule ^ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

## ROUTER HTTPS Redirect
#RewriteCond %{HTTP:X-Forwarded-Proto} !https
#RewriteCond %{HTTPS} off
#RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# ROUTER URL Rewrite
RewriteCond %{SCRIPT_FILENAME} !-f
RewriteCond %{SCRIPT_FILENAME} !-d
RewriteRule ^(.*)$ index.php?route=/$1 [L,QSA]
</code></pre>
            </div>
        </card>
    </div>
</div>

<!-- index.php -->
<div class="card mb-3">
    <div class="card-header">
        4. Create the <strong>index.php</strong> file in root ofthe project folder.
    </div>
    <div class="card-body">
        <p class="card-text">
            This file is the first file called by .htaccess, so it's responsible to manage the routes. You can customize it
            as you needed, but be careful because it can impacte all framework functions. We strongly recomends then you
            customize you own routes as indicated.
        </p>
        <card class="card border-secondary m-3">
            <div class="card-body">
<pre><code>
ob_start();
date_default_timezone_set('America/Sao_Paulo');
require __DIR__ . "/vendor/autoload.php";

/**
 * BOOTSTRAP
 */

use BetoCampoy\ChampsFramework\Session;
use BetoCampoy\ChampsFramework\Router\Router;
use function ICanBoogie\pluralize;

$session = new Session();
$route = new Router(url(), ":");
$route->namespace("Source\App");

/**
 * EXAMPLE THEME ROUTES
 */
$route->group(null);
$route->get("/", "WebExample:home");
$route->get("/terms", "WebExample:terms");
$route->get("/contact", "WebExample:contact");

/**
 * CREATE YOUR CUSTOM ROUTES BELOW
 */


/**
 * CREATE YOUR CUSTOM ROUTES ABOVE
 */

/**
 * ROUTE DISPATCH
 */
$route->dispatch();


/**
 * ERROR REDIRECT
 */
if ($route->error()) {
    $route->redirect( $route->route("default.error", ["errcode" => $route->error()]));
}

ob_end_flush();
</code></pre>
            </div>
        </card>
    </div>
</div>

<!-- constants.php -->
<div class="card mb-3">
    <div class="card-header">
        5. Define required environmet constants.
    </div>
    <div class="card-body">
        <p class="card-text">
            The file <strong>Source/Boot/Constants.php</strong> is the right place to define <strong>ALL</strong>
            framework's constants.
        </p>
        <p class="card-text">
            You don't need to create it manually, after create te files above, access the
            project URL and all requered structure will be automatically created.
        </p>
        <p class="card-text">
            There are many framework constants, consult <a href="<?=url("/champs-docs/constants")?>">documentation</a> for a
            complete reference. But only the list bellow are required.
        </p>
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">

                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-start">
                                <div class="ms-2 me-auto">
                                    <div class="fw-bold">CHAMPS_SESSION_NAME</div>
                                    <p class="card-text">
                                        Define a UNIQUE name for session to avoid multiples CHAMPSframework application running
                                        in server share the same session.
                                    </p>
                                    <p class="card-text">
                                    <pre><code>define('CHAMPS_SESSION_NAME', "unique_session_name");</code></pre>
                                    </p>

                                </div>
                            </li>
                        </ul>

                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-start">
                                <div class="ms-2 me-auto">
                                    <div class="fw-bold">CHAMPS_ENVIRONMENT_IDENTIFIER</div>
                                    <p class="card-text">
                                        Define if the framework is running in Production (PRD), Development (DEV) or Test (UAT) environment.
                                    </p>
                                    <p class="card-text">
                                    <pre><code>define('CHAMPS_ENVIRONMENT_IDENTIFIER', "value");</code></pre>
                                    </p>

                                </div>
                            </li>
                        </ul>

                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-start">
                                <div class="ms-2 me-auto">
                                    <div class="fw-bold">CHAMPS_URL_XXX</div>
                                    <p class="card-text">
                                        Define if the framework is running in Production (PRD), Development (DEV) or Test (UAT) environment.
                                    </p>
                                    <p class="card-text">
                                    <pre>
                                        <code>
define('CHAMPS_URL_DEV', "http://development.url.project");
define('CHAMPS_URL_UAT', "http://test.url.project");
define('CHAMPS_URL_PRD', "http://production.url.project");
                                        </code>
                                    </pre>
                                    </p>

                                </div>
                            </li>
                        </ul>

                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-start">
                                <div class="ms-2 me-auto">
                                    <div class="fw-bold">CHAMPS_MINIFY_THEMES</div>
                                    <p class="card-text">
                                        Used tho minify the assets of frontend themes. A default web theme is installed as example,
                                        but you should remove it and create you own themes.
                                    </p>
                                    <p class="card-text">
                                        Customize this constant constant as you need, consult the
                                        <a href="<?=url("/champs-docs/minification")?>">ocumentation</a> for more datails about minification.
                                    </p>
                                    <p class="card-text text-warning">
                                        Delete this constant if you won't use the assets minification in your project.
                                    </p>
                                    <p class="card-text">
                                    <pre>
                                        <code>
define('CHAMPS_MINIFY_THEMES', [
    "themes" => [
        "web" => [
            "css" => [],
            "js" => [],
            "jquery-engine" => true
        ]
    ]
]);
                                        </code>
                                    </pre>
                                    </p>

                                </div>
                            </li>
                        </ul>

                    </div>
                </li>

            </ul>
        </div>
    </div>
</div>




